### ISSUE TITLE
Preview text for https://explorer.horizen.global insight shows false and irrelevant information.

### ISSUE THREAD

**Issue by PeaStew** [ZencashOfficial/insight-ui-zen#6]
https://media.discordapp.net/attachments/496336554135126026/703715478803054783/unknown.png

Preview text for https://explorer.horizen.global insight shows various info that is irrelevant including that it is on testnet(?!?).

@psyraxaus has adapted this for https://explorer.zen-solutions.io/ and this shows better information.

**Comment by cronicc** [comment]
Fixed in #9 thanks @psyraxaus
